alexa:
  filter:
    include_entities:
      - light.dining_room_chandelier_2
      - light.dining_room_cove_lights_2
      - light.dining_room_main_lights_2
      - light.kitchen_main_lights_2
      - light.main_bathroom_main_lights_2
      - light.main_bathroom_sconces_2
      - light.master_bedroom_ceiling_fan_light_2
      - light.nursery_sconces_2
      - light.hallway_main_lights_2
      - light.living_room
      - light.entryway_light
      - media_player.living_room_tv
      - media_player.denon_avr_x1500h
      - media_player.libreelec
      - sensor.nursery_temperature
      - sensor.dining_room_temperature
      - sensor.kitchen_temperature
      - switch.bedroom_ac_power
      - switch.living_room_3
      - switch.plug_3
      - switch.living_room_1
      - switch.living_room_2
      - automation.kitchen_lights_on
      - switch.nanit
      - group.lamps
    exclude_entities:
      - light.0x0017880106c01547_light
      - light.0x00178801089e29fe_light
      - light.0x00124b00210f64bc_light
      - light.0x00124b00210f7ca7_light
      - sensor.paul_s_2nd_echo_dot_next_alarm
      - sensor.paul_s_2nd_echo_dot_next_reminder
      - sensor.paul_s_2nd_echo_dot_next_timer
      - sensor.paul_s_3rd_echo_dot_next_alarm
      - sensor.paul_s_3rd_echo_dot_next_reminder
      - sensor.paul_s_3rd_echo_dot_next_timer
      - sensor.paul_s_alexa_web_interface_next_alarm
      - sensor.paul_s_alexa_web_interface_next_timer
      - sensor.paul_s_echo_dot_next_alarm
      - sensor.paul_s_echo_dot_next_reminder
      - sensor.paul_s_echo_dot_next_timer
      - sensor.paul_s_echo_next_alarm
      - sensor.paul_s_echo_next_reminder
      - sensor.paul_s_echo_next_timer
      - sensor.this_device_next_alarm
      - sensor.this_device_next_reminder
      - sensor.this_device_next_timer
      - switch.ac_cool
      - switch.ac_down
      - switch.ac_down_test
      - switch.ac_fan_down
      - switch.ac_fan_hi_test
      - switch.ac_fan_low_test
      - switch.ac_fan_only
      - switch.ac_fan_up
      - switch.ac_power
      - switch.ac_temp_down
      - switch.ac_temp_up
      - switch.ac_up_test
      - switch.ac_up
      - switch.bathroom3
      - switch.bedroom_ac_fan_down
      - switch.bedroom_ac_fan_up
      - switch.bedroom_ac_mode_switch
      - switch.bedroom_ac_temp_down
      - switch.bedroom_ac_temp_up
      - switch.bedroom_echo_dot_repeat_switch
      - switch.bedroom_echo_dot_shuffle_switch
      - switch.bedroom_echo_dot_do_not_disturb_switch
      - switch.bathroom_echo_dot_repeat_switch
      - switch.bathroom_echo_dot_shuffle_switch
      - switch.bathroom_echo_dot_do_not_disturb_switch
      - switch.kitchen_echo_dot_repeat_switch
      - switch.kitchen_echo_dot_shuffle_switch
      - switch.kitchen_echo_dot_do_not_disturb_switch
      - switch.dining_room_echo_repeat_switch
      - switch.dining_room_echo_shuffle_switch
      - switch.dining_room_echo_do_not_disturb_switch
      - switch.nursery_echo_dot_repeat_switch
      - switch.nursery_echo_dot_shuffle_switch
      - switch.nursery_echo_dot_do_not_disturb_switch
      - switch.everywhere_repeat_switch
      - switch.everywhere_shuffle_switch
      - switch.everywhere_do_not_disturb_switch
      - switch.paul_s_2nd_echo_dot_do_not_disturb_switch
      - switch.paul_s_2nd_echo_dot_repeat_switch
      - switch.paul_s_2nd_echo_dot_shuffle_switch
      - switch.paul_s_3rd_echo_dot_do_not_disturb_switch
      - switch.paul_s_3rd_echo_dot_repeat_switch
      - switch.paul_s_3rd_echo_dot_shuffle_switch
      - switch.paul_s_4th_echo_dot_do_not_disturb_switch
      - switch.paul_s_4th_echo_dot_shuffle_switch
      - switch.paul_s_4th_echo_dot_repeat_switch
      - switch.paul_s_alexa_apps_do_not_disturb_switch
      - switch.paul_s_alexa_apps_do_not_disturb_switch_2
      - switch.paul_s_alexa_web_interface_do_not_disturb_switch
      - switch.paul_s_alexa_web_interface_repeat_switch
      - switch.paul_s_alexa_web_interface_shuffle_switch
      - switch.paul_s_echo_do_not_disturb_switch
      - switch.paul_s_echo_dot_do_not_disturb_switch
      - switch.paul_s_echo_dot_repeat_switch
      - switch.paul_s_echo_dot_shuffle_switch
      - switch.paul_s_echo_repeat_switch
      - switch.paul_s_echo_shuffle_switch
      - switch.plug_1
      - switch.plug_2
      - switch.plug_4
      - switch.plug_5
      - switch.plug_6
      - switch.this_device_do_not_disturb_switch
      - switch.this_device_do_not_disturb_switch_2
      - switch.unnamed_device
      - switch.unnamed_device_2
      - switch.unnamed_device_3
      - switch.living_room_4
      - switch.switchbot
    include_domains:
      - light
      - switch
      - group
      - script
      - scene
      - media_players
  entity_config:
    light.hallway_main_lights_2:
      name: Hallway
      description: The light in the Hallway
      display_categories: LIGHT
    light.kitchen_main_lights_2:
      name: Kitchen Lights
      description: The lights in the Kitchen
      display_categories: LIGHT
    light.nursery_sconces_2:
      name: Nursery Light
      description: The lights in the Nursery
      display_categories: LIGHT
    light.dining_room_chandelier_2:
      name: Chandelier
      description: The chandelier in the Dining Room
      display_categories: LIGHT
    light.main_bathroom_sconces_2:
      name: Sconces
      description: The sconces in the Bathroom
      display_categories: LIGHT
    light.main_bathroom_main_lights_2:
      name: Bathroom
      description: The light in the Bathroom
      display_categories: LIGHT
    light.dining_room_cove_lights_2:
      name: Cove Light
      description: The cove lighting in the dining room
      display_categories: LIGHT
    light.dining_room_main_lights_2:
      name: Cans
      description: The can lights in the Dining Room
      display_categories: LIGHT
    light.master_bedroom_ceiling_fan_light_2:
      name: Bedroom
      description: The bedroom ceiling fan light
      display_categories: LIGHT
    light.living_room:
      name: Living Room Light
      description: The light in the living room
      display_categories: LIGHT
    light.entryway_light:
      name: Entryway
      description: The Entryway light
      display_categories: LIGHT
    light.living_room_lamp:
      name: Living Room Lamp
      description: The Lamp in the Living Room
      display_categories: LIGHT
    switch.bedroom_1:
      name: Pasha's Lamp
      description: The lamp by Pasha
      display_categories: SWITCH
    switch.bedroom_2:
      name: Caitlin's Lamp
      description: The lamp by Caitlin
      display_categories: SWITCH
    switch.bedroom_3:
      name: White Noise Machine
      description: The white noise Machine
      display_categories: SWITCH
    switch.fridge:
      name: Baby Lamp
      description: The lamp by the baby
      display_categories: SWITCH
    switch.kitchen1:
      name: Vitamix
      description: The Hi-speed blender
      display_categories: SWITCH
    switch.kitchen2:
      name: Hot Water Heater
      description: The hot water heater
      display_categories: SWITCH
    switch.kitchen3:
      name: Toaster
      description: The Toaster
      display_categories: SWITCH
    switch.kitchen4:
      name: Grinder
      description: The Coffee Grinder
      display_categories: SWITCH
    switch.bathroom:
      name: Shaver
      description: Braun Series 7
      display_categories: SWITCH
    switch.bathroom2:
      name: Hair Dryer
      description: The Dyson Hair Dryer
      display_categories: SWITCH
    media_player.living_room_tv:
      name: TV
      description: The TV in the living room
      display_categories: TV
    media_player.libreelec:
      name: Kodi
      description: The media player in the Living ROom
      display_categories: TV
    switch.ac_power_test:
      name: A C
      description: The A C in the Dining Room
      display_categories: SWITCH
    switch.bedroom_ac_power:
      name: Bedroom A C
      description: The A C in the Bedroom
      display_categories: SWITCH
    media_player.denon_avr_x1500h:
      name: Living Room Denon
      description: The denon in the living room
      display_categories: MUSIC_SYSTEM
    switch.denon_heos_music:
      name: Denon Spotify Test
      description: Testing Spotify with the Denon
      display_categories: SWITCH
    switch.netflix:
      name: Netflix
      description: My Netflix Switch
      display_categories: SWITCH
    switch.switchbot_2:
      name: The Front Door
      description: The Front Door
      display_categories: SWITCH
#    switch.living_room_3:
 #    name: The Living Room Lamp
  #   description: The Lamp in the Living Room
    switch.plug_3:
      name: Christmas Tree Lights
      description: The XMAS tree lights
      display_categories: SWITCH
    sensor.nursery_temperature:
      name: Nursery
      description: The thermometer in the nursery
      display_categories: TEMPERATURE_SENSOR
    sensor.dining_room_temperature:
      name: Dining Room
      description: The thermometer in the Dining room
      display_categories: TEMPERATURE_SENSOR
    sensor.kitchen_temperature:
      name: Kitchen
      description: The Thermometer in the Kitchen
      display_categories: TEMPERATURE_SENSOR
    switch.living_room_1:
      name: Heater
      description: The space heater in the Nursery
      display_categories: SWITCH
    switch.living_room_2:
      name: Humidifier
      description: The Humidifier in The Nursery
      display_categories: SWITCH
    switch.nanit:
      name: Nanit
      description: The Nanit Automation
      display_categories: SWITCH
    switch.kitchen_nanit:
      name: Kitchen Nanit
      description: The Kitchen Nanit Automation
      display_categories: SWITCH
    #switch.door:
    #  name: Door
    # description: The buildings front door
    # display_categories: DOOR
    switch.kitchen_door:
      name: Door
      description: The buildings front door, but from the kitchen
      display_categories: DOOR
    group.lamps:
      name: The Lamps
      description: The Lamps in the bedroom
      display_categories: SWITCH