- id: '1587820890176'
  name: Morning Lights
  entities:
    light.dining_room_chandelier:
      area_name: Dining Room
      brightness: 160
      friendly_name: Dining Room Chandelier
      integration_id: 7
      state: 'on'
      supported_features: 33
    light.dining_room_cove_lights:
      area_name: Dining Room
      brightness: 93
      friendly_name: Dining Room Cove Lights
      integration_id: 9
      state: 'on'
      supported_features: 33
    light.dining_room_main_lights:
      area_name: Dining Room
      brightness: 26
      friendly_name: Dining Room Main Lights
      integration_id: 8
      state: 'on'
      supported_features: 33
